import { FamilyPost, Match, PhotoItem, ShortVideo, Sponsor } from '@/types/tournament';

export const INITIAL_MATCHES: Match[] = [
  // LUNES 05 OCT · FÚTBOL FEMENINO · Cancha de La Garita Nueva
  {
    id: 'j1-fut-fem-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '15:30',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'cria',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 1,
    awayScore: 1,
    status: 'completed',
    currentPeriod: 'Finalizado',
    notes: 'Jornada 1 - Fútbol Femenino (Empate 1-1)',
    updatedAt: '2026-10-05T16:15:00Z',
  },
  {
    id: 'j1-fut-fem-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '15:30',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'la-paz-tempisque',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    status: 'completed',
    currentPeriod: 'Finalizado (W.O.)',
    walkover: 'away_forfeit',
    notes: 'Monseñor Vittorino no se presentó · Puntos asignados a La Paz Tempisque',
    updatedAt: '2026-10-05T16:00:00Z',
  },
  {
    id: 'j1-fut-fem-03',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '16:00',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'la-paz-tempisque',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 0,
    awayScore: 3,
    status: 'completed',
    currentPeriod: 'Finalizado',
    notes: 'Jornada 1 - Fútbol Femenino (Triunfo La Paz Cabo Velas 3-0)',
    updatedAt: '2026-10-05T16:45:00Z',
  },
  {
    id: 'j1-fut-fem-04',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '16:45',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'cria',
    awayTeamId: 'la-paz-tempisque',
    homeScore: 1,
    awayScore: 1,
    status: 'completed',
    currentPeriod: 'Finalizado',
    notes: 'Jornada 1 - Fútbol Femenino (Empate 1-1)',
    updatedAt: '2026-10-05T17:30:00Z',
  },

  // MARTES 06 OCT · FÚTBOL C · Cancha de La Garita Nueva
  {
    id: 'j1-fut-c-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-10-06',
    time: '15:15',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'cria',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 0,
    awayScore: 1,
    status: 'completed',
    currentPeriod: 'Finalizado',
    notes: 'Jornada 1 - Fútbol Categoría C (Triunfo La Paz Cabo Velas 1-0)',
    updatedAt: '2026-10-06T15:45:00Z',
  },
  {
    id: 'j1-fut-c-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-10-06',
    time: '15:15',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'la-paz-tempisque',
    awayTeamId: 'journey-school',
    homeScore: 9,
    awayScore: 0,
    status: 'completed',
    currentPeriod: 'Finalizado',
    notes: 'Jornada 1 - Fútbol Categoría C (Triunfo La Paz Tempisque 9-0)',
    updatedAt: '2026-10-06T15:45:00Z',
  },
  {
    id: 'j1-fut-c-03',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-10-06',
    time: '16:00',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'vittorino',
    awayTeamId: 'cria',
    homeScore: 0,
    awayScore: 0,
    status: 'completed',
    currentPeriod: 'Finalizado',
    walkover: 'home_forfeit',
    notes: 'Monseñor Vittorino no se presentó · Puntos asignados a CRIA',
    updatedAt: '2026-10-06T16:30:00Z',
  },
  {
    id: 'j1-fut-c-04',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-10-06',
    time: '16:00',
    venue: 'Cancha de La Garita Nueva',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'la-paz-tempisque',
    homeScore: 2,
    awayScore: 0,
    status: 'completed',
    currentPeriod: 'Finalizado',
    notes: 'Jornada 1 - Fútbol Categoría C (Triunfo La Paz Cabo Velas 2-0)',
    updatedAt: '2026-10-06T16:45:00Z',
  },

  // MIÉRCOLES 07 OCT · FÚTBOL D · CRIA
  {
    id: 'j1-fut-d-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-d-futbol',
    sport: 'futbol',
    date: '2026-10-07',
    time: '15:15',
    venue: 'CRIA',
    homeTeamId: 'cria',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Fútbol Categoría D (3:15 pm)',
    updatedAt: '2026-10-07T15:15:00Z',
  },
  {
    id: 'j1-fut-d-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-d-futbol',
    sport: 'futbol',
    date: '2026-10-07',
    time: '15:15',
    venue: 'CRIA',
    homeTeamId: 'la-paz-tempisque',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    status: 'postponed',
    currentPeriod: 'Reprogramado',
    notes: 'SE REPROGRAMA',
    updatedAt: '2026-10-07T15:15:00Z',
  },

  // JUEVES 08 OCT · VOLEIBOL FEMENINO · Arena La Paz
  {
    id: 'j1-vol-c-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-voleibol',
    sport: 'voleibol',
    date: '2026-10-08',
    time: '15:15',
    venue: 'Arena La Paz',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    homeSetsWon: 0,
    awaySetsWon: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Voleibol Femenino Categoría C (3:15 pm)',
    updatedAt: '2026-10-08T15:15:00Z',
  },
  {
    id: 'j1-vol-c-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-voleibol',
    sport: 'voleibol',
    date: '2026-10-08',
    time: '16:00',
    venue: 'Arena La Paz',
    homeTeamId: 'educarte',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    homeSetsWon: 0,
    awaySetsWon: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Voleibol Femenino Categoría C (4:00 pm)',
    updatedAt: '2026-10-08T16:00:00Z',
  },
  {
    id: 'j1-vol-d-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-d-voleibol',
    sport: 'voleibol',
    date: '2026-10-08',
    time: '16:45',
    venue: 'Arena La Paz',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    homeSetsWon: 0,
    awaySetsWon: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Voleibol Femenino Categoría D (4:45 pm)',
    updatedAt: '2026-10-08T16:45:00Z',
  },

  // VIERNES 09 OCT · BALONCESTO · CRIA
  {
    id: 'j1-bal-c-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-c-baloncesto',
    sport: 'baloncesto',
    date: '2026-10-09',
    time: '15:15',
    venue: 'CRIA',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'la-paz-tempisque',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Baloncesto Categoría C (3:15 pm) · Descansa: Educarte',
    updatedAt: '2026-10-09T15:15:00Z',
  },
  {
    id: 'j1-bal-d-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-d-baloncesto',
    sport: 'baloncesto',
    date: '2026-10-09',
    time: '16:15',
    venue: 'CRIA',
    homeTeamId: 'journey-school',
    awayTeamId: 'la-paz-tempisque',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Baloncesto Categoría D (4:15 pm)',
    updatedAt: '2026-10-09T16:15:00Z',
  },
  {
    id: 'j1-bal-d-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: 'Jornada 1 · Festival Deportivo',
    categoryId: 'cat-d-baloncesto',
    sport: 'baloncesto',
    date: '2026-10-09',
    time: '17:15',
    venue: 'CRIA',
    homeTeamId: 'cria',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Jornada 1 - Baloncesto Categoría D (5:15 pm)',
    updatedAt: '2026-10-09T17:15:00Z',
  },
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'sp-conchal',
    name: 'Reserva Conchal Golf & Resort',
    categoryTag: 'Hotelería y Eventos Exclusivos',
    tier: 'Diamante',
    logoUrl: '🏨',
    bannerUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    promoTitle: '15% de Descuento Exclusivo para Familias de la Liga',
    promoDescription: 'Disfruta de estadías inolvidables, canchas de golf y gastronomía internacional en Playa Conchal presentando tu código digital.',
    couponCode: 'COSTAORO15',
    discountPercentage: 15,
    whatsappUrl: 'https://wa.me/50688880001?text=Hola%2C%20quisiera%20aplicar%20el%20cup%C3%B3n%20COSTAORO15%20de%20la%20Liga%20Costa%20de%20Oro.',
    websiteUrl: 'https://reservaconchal.com',
    currentClicks: 142,
    estimatedImpressions: 2850,
  },
  {
    id: 'sp-watersports',
    name: 'Guanacaste Water Sports & Surf',
    categoryTag: 'Aventura y Deportes Acuáticos',
    tier: 'Oro',
    logoUrl: '🏄‍♂️',
    bannerUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
    promoTitle: '20% en Clases de Surf y Tours en Catamarán',
    promoDescription: 'Equipamiento premium y guías certificados para vivir la costa de Guanacaste al máximo con tarifas especiales de torneo.',
    couponCode: 'SURFCOSTA20',
    discountPercentage: 20,
    whatsappUrl: 'https://wa.me/50688880002?text=Hola%2C%20vengo%20del%20portal%20de%20la%20Liga%20Costa%20de%20Oro%20con%20el%20cup%C3%B3n%20SURFCOSTA20.',
    websiteUrl: 'https://guanacastewatersports.cr',
    currentClicks: 98,
    estimatedImpressions: 1940,
  },
  {
    id: 'sp-britt',
    name: 'Café Britt Guanacaste',
    categoryTag: 'Cafetería Gourmet & Snacks',
    tier: 'Oro',
    logoUrl: '☕',
    bannerUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80',
    promoTitle: 'Degustación y 10% de Ahorro en Cafetería',
    promoDescription: 'El mejor café gourmet de Costa Rica y chocolates artesanales disponibles en nuestros quioscos durante los festivales deportivos.',
    couponCode: 'LIGABRITT10',
    discountPercentage: 10,
    whatsappUrl: 'https://wa.me/50688880003?text=Hola%2C%20quiero%20conocer%20las%20promociones%20de%20Caf%C3%A9%20Britt%20para%20la%20Liga%20Costa%20de%20Oro.',
    websiteUrl: 'https://britt.cr',
    currentClicks: 84,
    estimatedImpressions: 1620,
  },
  {
    id: 'sp-hospital',
    name: 'Hospital Metropolitano Huacas',
    categoryTag: 'Salud y Medicina Deportiva',
    tier: 'Plata',
    logoUrl: '🏥',
    bannerUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    promoTitle: 'Atención Médica y Fisioterapia Preferencial',
    promoDescription: 'Respaldo médico oficial, ambulancia en sitio y consultas de fisioterapia deportiva con atención rápida para todos los atletas.',
    couponCode: 'SALUDATLETA',
    discountPercentage: 10,
    whatsappUrl: 'https://wa.me/50688880004?text=Hola%2C%20requiero%20informaci%C3%B3n%20de%20fisioterapia%20deportiva%20Liga%20Costa%20de%20Oro.',
    websiteUrl: 'https://metropolitano.cr',
    currentClicks: 56,
    estimatedImpressions: 1200,
  },
];

export const INITIAL_SHORT_VIDEOS: ShortVideo[] = [];

export const INITIAL_PHOTOS: PhotoItem[] = [];

export const INITIAL_FAMILY_POSTS: FamilyPost[] = [
  {
    id: 'fp-welcome-01',
    schoolId: 'la-paz-cabo-velas',
    authorName: 'Comité Organizador Costa de Oro',
    authorRelation: 'Familia',
    message: '¡Bienvenidos a la fiesta deportiva y formativa de Guanacaste 2026! Este muro es el punto de encuentro para compartir saludos, mensajes de apoyo, fotos y celebrar el esfuerzo de todos los estudiantes.',
    mediaType: 'none',
    sportId: 'futbol',
    isFeatured: true,
    likesCount: 24,
    applauseCount: 18,
    featuredVotes: 9,
    createdAt: 'Hace un momento',
    comments: [
      {
        id: 'comm-welcome-01',
        authorName: 'Comunidad La Paz',
        text: '¡Éxitos a todas las 6 delegaciones en esta hermosa jornada deportiva!',
        createdAt: 'Hace unos instantes',
      },
    ],
  },
  {
    id: 'fp-welcome-02',
    schoolId: 'la-paz-cabo-velas',
    authorName: 'Familia Sharks',
    authorRelation: 'Familia',
    message: '¡Con todo Peace Sharks Cabo Velas! A dejar el corazón en la cancha con respeto, pasión y juego limpio. 🦈⚽',
    mediaType: 'none',
    sportId: 'futbol',
    isFeatured: true,
    likesCount: 15,
    applauseCount: 12,
    featuredVotes: 6,
    createdAt: 'Hace un momento',
    comments: [],
  },
  {
    id: 'fp-welcome-03',
    schoolId: 'la-paz-tempisque',
    authorName: 'Familia Tempisque',
    authorRelation: 'Familia',
    message: '¡Fuerza La Paz Tempisque! Muy orgullosos de la entrega y el trabajo en equipo de nuestros chicos. ¡A disfrutar! 💙',
    mediaType: 'none',
    sportId: 'voleibol',
    isFeatured: false,
    likesCount: 11,
    applauseCount: 8,
    featuredVotes: 4,
    createdAt: 'Hace un momento',
    comments: [],
  },
  {
    id: 'fp-welcome-04',
    schoolId: 'cria',
    authorName: 'Familia Dolphins',
    authorRelation: 'Familia',
    message: '¡Go Dolphins! Con toda la energía y disciplina que caracteriza a CRIA. ¡Gran festival deportivo para todos! 🐬✨',
    mediaType: 'none',
    sportId: 'baloncesto',
    isFeatured: false,
    likesCount: 14,
    applauseCount: 10,
    featuredVotes: 5,
    createdAt: 'Hace un momento',
    comments: [],
  },
  {
    id: 'fp-welcome-05',
    schoolId: 'journey-school',
    authorName: 'Comunidad Journey',
    authorRelation: 'Familia',
    message: '¡Vamos The Journey School! Pasión, compañerismo y mucho aprendizaje en cada jugada. ¡Estamos con ustedes! 🔥👏',
    mediaType: 'none',
    sportId: 'baloncesto',
    isFeatured: false,
    likesCount: 12,
    applauseCount: 9,
    featuredVotes: 4,
    createdAt: 'Hace un momento',
    comments: [],
  },
  {
    id: 'fp-welcome-06',
    schoolId: 'vittorino',
    authorName: 'Familia Vittorino',
    authorRelation: 'Familia',
    message: '¡Con la frente en alto Monseñor Vittorino! Valores, fe y espíritu deportivo en cada encuentro. ¡Adelante jóvenes! 🏆',
    mediaType: 'none',
    sportId: 'voleibol',
    isFeatured: false,
    likesCount: 13,
    applauseCount: 11,
    featuredVotes: 5,
    createdAt: 'Hace un momento',
    comments: [],
  },
  {
    id: 'fp-welcome-07',
    schoolId: 'educarte',
    authorName: 'Comunidad Educarte',
    authorRelation: 'Familia',
    message: '¡Orgullo total Educarte! A vivir el deporte con alegría, amistad y sana convivencia. ¡Vamos equipo! ⚽🏐🏀',
    mediaType: 'none',
    sportId: 'futbol',
    isFeatured: false,
    likesCount: 16,
    applauseCount: 14,
    featuredVotes: 6,
    createdAt: 'Hace un momento',
    comments: [],
  },
];


