import { Match, PhotoItem, ShortVideo, Sponsor } from '@/types/tournament';

export const INITIAL_MATCHES: Match[] = [
  // JORNADA 1 - Partidos de Prueba (Todos en 0 - 0)
  {
    id: 'm-fem-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '13:30',
    venue: 'Cancha Principal, Campus Cabo Velas',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'cria',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-05T10:00:00Z',
  },
  {
    id: 'm-fem-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '15:00',
    venue: 'Cancha Principal, Campus Cabo Velas',
    homeTeamId: 'journey-school',
    awayTeamId: 'educarte',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-05T10:00:00Z',
  },
  {
    id: 'm-fem-03',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-10-05',
    time: '16:15',
    venue: 'Cancha 2, Campus Cabo Velas',
    homeTeamId: 'la-paz-tempisque',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-05T10:00:00Z',
  },
  // Fútbol Masculino Cat C
  {
    id: 'm-fut-c-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-10-06',
    time: '13:30',
    venue: 'Cancha Principal, Campus Tempisque',
    homeTeamId: 'cria',
    awayTeamId: 'la-paz-tempisque',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-06T10:00:00Z',
  },
  {
    id: 'm-fut-c-02',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-10-06',
    time: '15:00',
    venue: 'Cancha Principal, Campus Tempisque',
    homeTeamId: 'educarte',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-06T10:00:00Z',
  },
  // Fútbol Masculino Cat D
  {
    id: 'm-fut-d-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-d-futbol',
    sport: 'futbol',
    date: '2026-10-07',
    time: '14:00',
    venue: 'Cancha Sintética, Campus Cabo Velas',
    homeTeamId: 'vittorino',
    awayTeamId: 'journey-school',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-07T10:00:00Z',
  },
  // Voleibol Femenino Cat C
  {
    id: 'm-vol-c-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-c-voleibol',
    sport: 'voleibol',
    date: '2026-10-08',
    time: '13:30',
    venue: 'Gimnasio Techado, Campus Tempisque',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'journey-school',
    homeScore: 0,
    awayScore: 0,
    homeSetsWon: 0,
    awaySetsWon: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-08T10:00:00Z',
  },
  // Baloncesto Cat C
  {
    id: 'm-bal-c-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 1,
    jornadaName: '1.ª Jornada - Festival Octubre',
    categoryId: 'cat-c-baloncesto',
    sport: 'baloncesto',
    date: '2026-10-09',
    time: '14:30',
    venue: 'Cancha Múltiple, Campus Cabo Velas',
    homeTeamId: 'cria',
    awayTeamId: 'vittorino',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-09T10:00:00Z',
  },
  // PRÓXIMO ENCUENTRO OFICIAL PROGRAMADO (JORNADA 2)
  {
    id: 'm-fem-j2-01',
    tournamentId: 'costa-de-oro-2026',
    jornada: 2,
    jornadaName: '2.ª Jornada - Festival Noviembre',
    categoryId: 'cat-fem-futbol',
    sport: 'futbol',
    date: '2026-11-02',
    time: '14:00',
    venue: 'Cancha Principal, Campus Tempisque',
    homeTeamId: 'la-paz-tempisque',
    awayTeamId: 'la-paz-cabo-velas',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Clásico institucional programado para la 2.ª Jornada Oficial.',
    updatedAt: '2026-10-15T10:00:00Z',
  },
  // PRÓXIMOS ENCUENTROS (Jornadas 2, 3 y Finales)
  {
    id: 'm-fut-c-next1',
    tournamentId: 'costa-de-oro-2026',
    jornada: 2,
    jornadaName: '2.ª Jornada - Festival Noviembre',
    categoryId: 'cat-c-futbol',
    sport: 'futbol',
    date: '2026-11-03',
    time: '13:30',
    venue: 'Cancha Principal, Campus Tempisque',
    homeTeamId: 'journey-school',
    awayTeamId: 'cria',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-20T10:00:00Z',
  },
  {
    id: 'm-vol-c-next1',
    tournamentId: 'costa-de-oro-2026',
    jornada: 2,
    jornadaName: '2.ª Jornada - Festival Noviembre',
    categoryId: 'cat-c-voleibol',
    sport: 'voleibol',
    date: '2026-11-05',
    time: '14:00',
    venue: 'Gimnasio Techado, Campus Cabo Velas',
    homeTeamId: 'educarte',
    awayTeamId: 'la-paz-tempisque',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-20T10:00:00Z',
  },
  {
    id: 'm-bal-c-next1',
    tournamentId: 'costa-de-oro-2026',
    jornada: 2,
    jornadaName: '2.ª Jornada - Festival Noviembre',
    categoryId: 'cat-c-baloncesto',
    sport: 'baloncesto',
    date: '2026-11-06',
    time: '15:00',
    venue: 'Cancha Múltiple, Campus Cabo Velas',
    homeTeamId: 'la-paz-cabo-velas',
    awayTeamId: 'educarte',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    currentPeriod: 'Por Iniciar',
    notes: 'Encuentro de prueba programado para calibración previa al torneo.',
    updatedAt: '2026-10-20T10:00:00Z',
  },
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'sp-conchal',
    name: 'Reserva Conchal Golf & Resort',
    categoryTag: 'Hotelería y Eventos Exclusivos',
    tier: 'Diamante',
    logoUrl: '🏨',
    bannerUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    promoTitle: '15% de Descuento Exclusivo para Familias de la Liga',
    promoDescription: 'Disfruta de estadías inolvidables, canchas de golf y gastronomía internacional en Playa Conchal presentando tu código digital.',
    couponCode: 'COSTAORO15',
    discountPercentage: 15,
    whatsappUrl: 'https://wa.me/50688880001?text=Hola%2C%20quisiera%20aplicar%20el%20cup%C3%B3n%20COSTAORO15%20de%20la%20Liga%20Costa%20de%20Oro.',
    websiteUrl: 'https://reservaconchal.com',
    currentClicks: 142,
    estimatedImpressions: 2850,
  },
  {
    id: 'sp-watersports',
    name: 'Guanacaste Water Sports & Surf',
    categoryTag: 'Aventura y Deportes Acuáticos',
    tier: 'Oro',
    logoUrl: '🏄‍♂️',
    bannerUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
    promoTitle: '20% en Clases de Surf y Tours en Catamarán',
    promoDescription: 'Equipamiento premium y guías certificados para vivir la costa de Guanacaste al máximo con tarifas especiales de torneo.',
    couponCode: 'SURFCOSTA20',
    discountPercentage: 20,
    whatsappUrl: 'https://wa.me/50688880002?text=Hola%2C%20vengo%20del%20portal%20de%20la%20Liga%20Costa%20de%20Oro%20con%20el%20cup%C3%B3n%20SURFCOSTA20.',
    websiteUrl: 'https://guanacastewatersports.cr',
    currentClicks: 98,
    estimatedImpressions: 1940,
  },
  {
    id: 'sp-britt',
    name: 'Café Britt Guanacaste',
    categoryTag: 'Cafetería Gourmet & Snacks',
    tier: 'Oro',
    logoUrl: '☕',
    bannerUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80',
    promoTitle: 'Degustación y 10% de Ahorro en Cafetería',
    promoDescription: 'El mejor café gourmet de Costa Rica y chocolates artesanales disponibles en nuestros quioscos durante los festivales deportivos.',
    couponCode: 'LIGABRITT10',
    discountPercentage: 10,
    whatsappUrl: 'https://wa.me/50688880003?text=Hola%2C%20quiero%20conocer%20las%20promociones%20de%20Caf%C3%A9%20Britt%20para%20la%20Liga%20Costa%20de%20Oro.',
    websiteUrl: 'https://britt.cr',
    currentClicks: 84,
    estimatedImpressions: 1620,
  },
  {
    id: 'sp-hospital',
    name: 'Hospital Metropolitano Huacas',
    categoryTag: 'Salud y Medicina Deportiva',
    tier: 'Plata',
    logoUrl: '🏥',
    bannerUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    promoTitle: 'Atención Médica y Fisioterapia Preferencial',
    promoDescription: 'Respaldo médico oficial, ambulancia en sitio y consultas de fisioterapia deportiva con atención rápida para todos los atletas.',
    couponCode: 'SALUDATLETA',
    discountPercentage: 10,
    whatsappUrl: 'https://wa.me/50688880004?text=Hola%2C%20requiero%20informaci%C3%B3n%20de%20fisioterapia%20deportiva%20Liga%20Costa%20de%20Oro.',
    websiteUrl: 'https://metropolitano.cr',
    currentClicks: 56,
    estimatedImpressions: 1200,
  },
];

export const INITIAL_SHORT_VIDEOS: ShortVideo[] = [
  {
    id: 'v-01',
    title: '¡Golazo al ángulo en el clásico de fútbol femenino!',
    authorName: 'Familia Méndez',
    authorRole: 'Familia',
    schoolId: 'la-paz-cabo-velas',
    categoryId: 'cat-fem-futbol',
    matchId: 'm-fem-01',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=500&q=80',
    durationSeconds: 18,
    likesCount: 64,
    viewsCount: 512,
    createdAt: '2026-10-05T16:00:00Z',
    approved: true,
  },
  {
    id: 'v-02',
    title: 'Tapón espectacular en el último cuarto de baloncesto',
    authorName: 'Coach Esteban',
    authorRole: 'Entrenador',
    schoolId: 'cria',
    categoryId: 'cat-c-baloncesto',
    matchId: 'm-bal-c-01',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=500&q=80',
    durationSeconds: 14,
    likesCount: 47,
    viewsCount: 389,
    createdAt: '2026-10-09T16:30:00Z',
    approved: true,
  },
  {
    id: 'v-03',
    title: 'Celebración del equipo tras el pase a la final de voleibol',
    authorName: 'Curiol Studio',
    authorRole: 'Curiol Studio',
    schoolId: 'la-paz-tempisque',
    categoryId: 'cat-c-voleibol',
    matchId: 'm-vol-c-01',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=500&q=80',
    durationSeconds: 22,
    likesCount: 89,
    viewsCount: 730,
    createdAt: '2026-10-08T15:15:00Z',
    approved: true,
  },
];

export const INITIAL_PHOTOS: PhotoItem[] = [
  {
    id: 'ph-01',
    title: 'Calentamiento y concentración previa al partido',
    categoryId: 'cat-fem-futbol',
    schoolId: 'la-paz-cabo-velas',
    jornada: 1,
    date: '2026-10-05',
    moment: 'previo',
    momentLabel: '1. Momento Previo (Enfoque & Calentamiento)',
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1000&q=80',
    photographer: 'Curiol Studio',
    viewsCount: 340,
    downloadUrl: '#',
  },
  {
    id: 'ph-02',
    title: 'Disputa de balón en el medio campo',
    categoryId: 'cat-fem-futbol',
    schoolId: 'cria',
    jornada: 1,
    date: '2026-10-05',
    moment: 'durante',
    momentLabel: '2. Momento Durante el Encuentro (Acción Pura)',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1000&q=80',
    photographer: 'Curiol Studio',
    viewsCount: 420,
    downloadUrl: '#',
  },
  {
    id: 'ph-03',
    title: 'Abrazo de equipo tras la victoria en voleibol',
    categoryId: 'cat-c-voleibol',
    schoolId: 'la-paz-cabo-velas',
    jornada: 1,
    date: '2026-10-08',
    moment: 'final_premiacion',
    momentLabel: '3. Momento Posterior & Celebración',
    imageUrl: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?w=1000&q=80',
    photographer: 'Curiol Studio',
    viewsCount: 290,
    downloadUrl: '#',
  },
  {
    id: 'ph-04',
    title: 'Salto al aro en la categoría C de baloncesto',
    categoryId: 'cat-c-baloncesto',
    schoolId: 'vittorino',
    jornada: 1,
    date: '2026-10-09',
    moment: 'durante',
    momentLabel: '2. Momento Durante el Encuentro (Acción Pura)',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1000&q=80',
    photographer: 'Curiol Studio',
    viewsCount: 310,
    downloadUrl: '#',
  },
];
